package com.alessandro.astages.api.reload;

public enum ClientReloadPhase {
    PLAYER_CONNECTED,

    PLAYER_LOGGED_IN,

    STAGES_SYNCED,

    ITEM_RESTRICTION_MARKED_AS_DIRTY,
    RECIPE_RESTRICTION_MARKED_AS_DIRTY,
    ORE_RESTRICTION_MARKED_AS_DIRTY,

    RELOAD_STARTED,
    RELOAD_FINISHED,

    RECIPE_VIEWERS_BUILD_CACHE,

    PLAYER_LOGGED_OUT,

    PLAYER_DISCONNECTED

}